/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Text;
export const ReviewId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BannerId = IDL.Text;
export const Banner = IDL.Record({
  'id' : BannerId,
  'title' : IDL.Text,
  'order' : IDL.Int,
  'isActive' : IDL.Bool,
  'ctaLink' : IDL.Text,
  'imageUrl' : IDL.Text,
  'ctaText' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const BlogPostId = IDL.Text;
export const BlogPost = IDL.Record({
  'id' : BlogPostId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'imageUrl' : IDL.Text,
  'artisanId' : IDL.Opt(IDL.Text),
});
export const FestivalCollectionId = IDL.Text;
export const FestivalCollection = IDL.Record({
  'id' : FestivalCollectionId,
  'productIds' : IDL.Vec(ProductId),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'festivalDate' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'originalPrice' : IDL.Nat,
  'stockQty' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'isNewArrival' : IDL.Bool,
  'description' : IDL.Text,
  'additionalImages' : IDL.Vec(IDL.Text),
  'artisanStory' : IDL.Text,
  'artisanName' : IDL.Text,
  'state' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'craftType' : IDL.Text,
  'isBestseller' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'careInstructions' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderId = IDL.Text;
export const OrderItem = IDL.Record({
  'qty' : IDL.Int,
  'productId' : ProductId,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : IDL.Text,
  'trackingNumber' : IDL.Opt(IDL.Text),
  'total' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'guestEmail' : IDL.Opt(IDL.Text),
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ProductFilter = IDL.Record({
  'tag' : IDL.Opt(IDL.Text),
  'isNewArrival' : IDL.Opt(IDL.Bool),
  'search' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'state' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Opt(IDL.Bool),
  'craftType' : IDL.Opt(IDL.Text),
  'isBestseller' : IDL.Opt(IDL.Bool),
  'category' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func(
      [ProductId, IDL.Text, IDL.Nat, IDL.Text],
      [ReviewId],
      [],
    ),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBanner' : IDL.Func([Banner], [BannerId], []),
  'createBlogPost' : IDL.Func([BlogPost], [BlogPostId], []),
  'createFestivalCollection' : IDL.Func(
      [FestivalCollection],
      [FestivalCollectionId],
      [],
    ),
  'createProduct' : IDL.Func([Product], [ProductId], []),
  'deleteBanner' : IDL.Func([BannerId], [], []),
  'deleteBlogPost' : IDL.Func([BlogPostId], [], []),
  'deleteFestivalCollection' : IDL.Func([FestivalCollectionId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listFestivalCollections' : IDL.Func(
      [],
      [IDL.Vec(FestivalCollection)],
      ['query'],
    ),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'placeGuestOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(OrderItem), IDL.Nat, IDL.Text],
      [OrderId],
      [],
    ),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Nat, IDL.Text],
      [OrderId],
      [],
    ),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBanner' : IDL.Func([BannerId, Banner], [Banner], []),
  'updateBlogPost' : IDL.Func([BlogPostId, BlogPost], [BlogPost], []),
  'updateFestivalCollection' : IDL.Func(
      [FestivalCollectionId, FestivalCollection],
      [FestivalCollection],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [OrderId, IDL.Text, IDL.Opt(IDL.Text)],
      [Order],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, Product], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Text;
  const ReviewId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BannerId = IDL.Text;
  const Banner = IDL.Record({
    'id' : BannerId,
    'title' : IDL.Text,
    'order' : IDL.Int,
    'isActive' : IDL.Bool,
    'ctaLink' : IDL.Text,
    'imageUrl' : IDL.Text,
    'ctaText' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const BlogPostId = IDL.Text;
  const BlogPost = IDL.Record({
    'id' : BlogPostId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'imageUrl' : IDL.Text,
    'artisanId' : IDL.Opt(IDL.Text),
  });
  const FestivalCollectionId = IDL.Text;
  const FestivalCollection = IDL.Record({
    'id' : FestivalCollectionId,
    'productIds' : IDL.Vec(ProductId),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'festivalDate' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'originalPrice' : IDL.Nat,
    'stockQty' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'isNewArrival' : IDL.Bool,
    'description' : IDL.Text,
    'additionalImages' : IDL.Vec(IDL.Text),
    'artisanStory' : IDL.Text,
    'artisanName' : IDL.Text,
    'state' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'craftType' : IDL.Text,
    'isBestseller' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'careInstructions' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderId = IDL.Text;
  const OrderItem = IDL.Record({
    'qty' : IDL.Int,
    'productId' : ProductId,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : IDL.Text,
    'trackingNumber' : IDL.Opt(IDL.Text),
    'total' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'guestEmail' : IDL.Opt(IDL.Text),
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ProductFilter = IDL.Record({
    'tag' : IDL.Opt(IDL.Text),
    'isNewArrival' : IDL.Opt(IDL.Bool),
    'search' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'state' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Opt(IDL.Bool),
    'craftType' : IDL.Opt(IDL.Text),
    'isBestseller' : IDL.Opt(IDL.Bool),
    'category' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func(
        [ProductId, IDL.Text, IDL.Nat, IDL.Text],
        [ReviewId],
        [],
      ),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBanner' : IDL.Func([Banner], [BannerId], []),
    'createBlogPost' : IDL.Func([BlogPost], [BlogPostId], []),
    'createFestivalCollection' : IDL.Func(
        [FestivalCollection],
        [FestivalCollectionId],
        [],
      ),
    'createProduct' : IDL.Func([Product], [ProductId], []),
    'deleteBanner' : IDL.Func([BannerId], [], []),
    'deleteBlogPost' : IDL.Func([BlogPostId], [], []),
    'deleteFestivalCollection' : IDL.Func([FestivalCollectionId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listFestivalCollections' : IDL.Func(
        [],
        [IDL.Vec(FestivalCollection)],
        ['query'],
      ),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'placeGuestOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(OrderItem), IDL.Nat, IDL.Text],
        [OrderId],
        [],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Nat, IDL.Text],
        [OrderId],
        [],
      ),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBanner' : IDL.Func([BannerId, Banner], [Banner], []),
    'updateBlogPost' : IDL.Func([BlogPostId, BlogPost], [BlogPost], []),
    'updateFestivalCollection' : IDL.Func(
        [FestivalCollectionId, FestivalCollection],
        [FestivalCollection],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [OrderId, IDL.Text, IDL.Opt(IDL.Text)],
        [Order],
        [],
      ),
    'updateProduct' : IDL.Func([ProductId, Product], [Product], []),
  });
};

export const init = ({ IDL }) => { return []; };