/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Banner {
  'id' : BannerId,
  'title' : string,
  'order' : bigint,
  'isActive' : boolean,
  'ctaLink' : string,
  'imageUrl' : string,
  'ctaText' : string,
  'subtitle' : string,
}
export type BannerId = string;
export interface BlogPost {
  'id' : BlogPostId,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'authorName' : string,
  'imageUrl' : string,
  'artisanId' : [] | [string],
}
export type BlogPostId = string;
export interface FestivalCollection {
  'id' : FestivalCollectionId,
  'productIds' : Array<ProductId>,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'festivalDate' : string,
}
export type FestivalCollectionId = string;
export interface Order {
  'id' : OrderId,
  'status' : string,
  'trackingNumber' : [] | [string],
  'total' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'guestEmail' : [] | [string],
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
}
export type OrderId = string;
export interface OrderItem {
  'qty' : bigint,
  'productId' : ProductId,
  'price' : bigint,
}
export interface Product {
  'id' : ProductId,
  'originalPrice' : bigint,
  'stockQty' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'isNewArrival' : boolean,
  'description' : string,
  'additionalImages' : Array<string>,
  'artisanStory' : string,
  'artisanName' : string,
  'state' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'craftType' : string,
  'isBestseller' : boolean,
  'category' : string,
  'price' : bigint,
  'careInstructions' : string,
}
export interface ProductFilter {
  'tag' : [] | [string],
  'isNewArrival' : [] | [boolean],
  'search' : [] | [string],
  'maxPrice' : [] | [bigint],
  'state' : [] | [string],
  'isFeatured' : [] | [boolean],
  'craftType' : [] | [string],
  'isBestseller' : [] | [boolean],
  'category' : [] | [string],
  'minPrice' : [] | [bigint],
}
export type ProductId = string;
export interface Review {
  'id' : ReviewId,
  'userName' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[ProductId, string, bigint, string], ReviewId>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBanner' : ActorMethod<[Banner], BannerId>,
  'createBlogPost' : ActorMethod<[BlogPost], BlogPostId>,
  'createFestivalCollection' : ActorMethod<
    [FestivalCollection],
    FestivalCollectionId
  >,
  'createProduct' : ActorMethod<[Product], ProductId>,
  'deleteBanner' : ActorMethod<[BannerId], undefined>,
  'deleteBlogPost' : ActorMethod<[BlogPostId], undefined>,
  'deleteFestivalCollection' : ActorMethod<[FestivalCollectionId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBanners' : ActorMethod<[], Array<Banner>>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listFestivalCollections' : ActorMethod<[], Array<FestivalCollection>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'placeGuestOrder' : ActorMethod<
    [string, Array<OrderItem>, bigint, string],
    OrderId
  >,
  'placeOrder' : ActorMethod<[Array<OrderItem>, bigint, string], OrderId>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBanner' : ActorMethod<[BannerId, Banner], Banner>,
  'updateBlogPost' : ActorMethod<[BlogPostId, BlogPost], BlogPost>,
  'updateFestivalCollection' : ActorMethod<
    [FestivalCollectionId, FestivalCollection],
    FestivalCollection
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, string, [] | [string]], Order>,
  'updateProduct' : ActorMethod<[ProductId, Product], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];